export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_REQUESTS_COUNT = 'SET_REQUESTS_COUNT';
export const SET_REQUESTS = 'SET_REQUESTS';
export const LOG_OUT = 'LOG_OUT';
