export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOG_OUT = 'LOG_OUT';
export const GET_DISTRICTS = 'GET_DISTRICTS';
export const GET_CONSTITUENCIES = 'GET_CONSTITUENCIES';
export const GET_MANDALS = 'GET_MANDALS';
export const GET_VILLAGES = 'GET_VILLAGES';
export const CREATE_REQUEST = 'CREATE_REQUEST';
